"""initial schema

Revision ID: d3a5f57a7c59
Revises: 
Create Date: 2026-06-15 19:44:31.779137
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a5f57a7c59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('auth_sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=128), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=128), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('meta_connections',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('meta_user_id', sa.String(length=128), nullable=False),
    sa.Column('meta_user_name', sa.String(length=255), nullable=False),
    sa.Column('access_token_encrypted', sa.String(), nullable=False),
    sa.Column('access_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('scopes', sa.String(length=512), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'meta_user_id', name='uq_meta_connection_user_meta_user')
    )
    op.create_index(op.f('ix_meta_connections_user_id'), 'meta_connections', ['user_id'], unique=False)
    op.create_table('meta_ad_accounts',
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('account_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=True),
    sa.Column('timezone_name', sa.String(length=64), nullable=True),
    sa.Column('account_status', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['meta_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'external_id', name='uq_meta_ad_account_connection_external')
    )
    op.create_index(op.f('ix_meta_ad_accounts_connection_id'), 'meta_ad_accounts', ['connection_id'], unique=False)
    op.create_index(op.f('ix_meta_ad_accounts_external_id'), 'meta_ad_accounts', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meta_ad_accounts_external_id'), table_name='meta_ad_accounts')
    op.drop_index(op.f('ix_meta_ad_accounts_connection_id'), table_name='meta_ad_accounts')
    op.drop_table('meta_ad_accounts')
    op.drop_index(op.f('ix_meta_connections_user_id'), table_name='meta_connections')
    op.drop_table('meta_connections')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
